import { makeStyles } from '@material-ui/styles';

export const useButtonStyles = makeStyles({
  mainOrange: {
    margin: '0 4px 0 4px',
    borderRadius: 6,
    fontSize: 14,
    fontWeight: 600,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    lineHeight: '100%',
    padding: '10px 32px',
    background: '#E9856B',
    color: '#ffffff',
    fontFamily: 'Gilroy, sans-serif',
    textTransform: 'none',
    transition: 'none',
    '&:hover': {
      textDecoration: 'none',
      backgroundColor: '#E9856B',
    },
  },
  mainGray: {
    margin: '0 4px 0 4px',
    borderRadius: 6,
    border: '1px solid #EBEEF5',
    fontSize: 14,
    fontWeight: 600,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    lineHeight: '100%',
    padding: '10px 32px',
    background: '#F5F7FD',
    fontFamily: 'Gilroy, sans-serif',
    textTransform: 'none',
    transition: 'none',
    '&:hover': {
      textDecoration: 'none',
      backgroundColor: '#F5F7FD',
    },
  },
  subGray: {
    borderRadius: 6,
    border: '1px solid #EBEEF5',
    fontSize: 14,
    fontWeight: 600,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    lineHeight: '100%',
    padding: '9px 16px',
    background: '#F5F7FD',
    fontFamily: 'Gilroy, sans-serif',
    textTransform: 'none',
    transition: 'none',
    '&:hover': {
      textDecoration: 'none',
      backgroundColor: '#F5F7FD',
    },
  },
});
